# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  configuration: release

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(configuration)
  displayName: 'print variable'

- script: echo $(Build.BuildNumber)
  displayName: 'print build number'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
