# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: configs
  type: string
  default: 'x86,x64'
  
trigger:
- master

variables:
  configuration: release

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      write-host 'my inline powershell'
      pwd
- script: echo $(configuration)
  displayName: 'print variable'

- script: echo $(Build.BuildNumber)
  displayName: 'print build number'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
